# Generated by Django 5.0.3 on 2024-04-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(choices=[('Avengers: Endgame', 'Avengers: Endgame'), ('The Shawshank Redemption', 'The Shawshank Redemption'), ('The Godfather', 'The Godfather'), ('The Dark Knight', 'The Dark Knight'), ('Pulp Fiction', 'Pulp Fiction')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
